services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-agent-api}:${IMAGE_TAG:-latest}
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      # API Keys
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ELEVEN_LABS_API_KEY: ${ELEVEN_LABS_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      # AGNO_API_KEY: ${AGNO_API_KEY}
      
      # Database Configuration - Cloud Database (Supabase/AWS RDS/etc)
      DB_URL: ${DB_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SCHEME: ${DB_SCHEME:-public}
      
      # Other settings
      WAIT_FOR_DB: "True"
      PRINT_ENV_ON_LOAD: "True"
    networks:
      - agent-api
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  agent-api: